import { VscVscode } from "react-icons/vsc";
import {
  SiTypescript,
  SiJavascript,
  SiNextdotjs,
  SiD3Dotjs,
  SiRedux,
  SiPostgresql,
  SiGraphql,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiJenkins,
  SiTravisci,
  SiGithub,
  SiLinux,
  SiNeovim,
  SiHtml5,
  SiReact,
  SiCss3,
  SiNodedotjs,
  SiDocker,
  SiGnubash,
  SiGtk,
  SiGnome,
  SiPhp,
  SiCurl,
  SiFigma,
  SiExpress,
  SiPostman,
} from "react-icons/si";
import { GoGitPullRequest } from "react-icons/go";
import { CgDesktop } from "react-icons/cg";

const techStack = [
  { name: "HTML", icon: SiHtml5, status: "using" },
  { name: "JavaScript", icon: SiJavascript, status: "using" },
  { name: "TypeScript", icon: SiTypescript, status: "using" },
  { name: "React", icon: SiReact, status: "using" },
  { name: "Next.js", icon: SiNextdotjs, status: "using" },
  { name: "D3", icon: SiD3Dotjs, status: "using" },
  { name: "Redux", icon: SiRedux, status: "plan" },
  { name: "CSS", icon: SiCss3, status: "using" },
  { name: "Sass (SCSS)", icon: SiSass, status: "using" },
  { name: "Bootstrap", icon: SiBootstrap, status: "using" },
  { name: "Tailwind", icon: SiTailwindcss, status: "using" },
  { name: "Node.js", icon: SiNodedotjs, status: "learning" },
  { name: "Express", icon: SiExpress, status: "learning" },
  { name: "PostgreSQL", icon: SiPostgresql, status: "learning" },
  { name: "GraphQL", icon: SiGraphql, status: "learning" },
  { name: "PHP", icon: SiPhp, status: "using" },
  { name: "CI/CD", icon: GoGitPullRequest, status: "plan" },
  { name: "Docker", icon: SiDocker, status: "plan" },
  { name: "GitHub Actions", icon: SiGithub, status: "plan" },
  { name: "Jenkins", icon: SiJenkins, status: "plan" },
  { name: "Travis CI", icon: SiTravisci, status: "plan" },
  { name: "Curl", icon: SiCurl, status: "learning" },
  { name: "Bash", icon: SiGnubash, status: "using" },
  { name: "Linux", icon: SiLinux, status: "using" },
  { name: "Neovim", icon: SiNeovim, status: "using" },
  { name: "VSCode/VSCodium", icon: VscVscode, status: "using" },
  { name: "GTK4", icon: SiGtk, status: "using" },
  { name: "GJS", icon: SiGnome, status: "using" },
  { name: "Astal", icon: CgDesktop, status: "using" },
  { name: "Figma", icon: SiFigma, status: "using" },
  { name: "GitHub", icon: SiGithub, status: "using" },
  { name: "Postman", icon: SiPostman, status: "plan" },
];

export default techStack;

